[package]
name = "dsmtool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
plotters = "0.3"
csv = "1.3.0"
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.214", features = ["derive"] }
rand = "0.8.5"
